upstream backend {
    server production-blue-backend-1:8000;
    server production-blue-backend-2:8000;
}

upstream frontend {
    server production-blue-frontend-1:3000;
    server production-blue-frontend-2:3000;
}