upstream backend {
    server production-green-backend-1:8000;
    server production-green-backend-2:8000;
}

upstream frontend {
    server production-green-frontend-1:3000;
    server production-green-frontend-2:3000;
}