name: Snyk Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 23 * * 5'

permissions:
  contents: read
  security-events: write

jobs:
  snyk-backend:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend Docker image
        run: |
          docker build -t ${{ vars.DOCKER_USER }}/erp-solution-backend:test ./backend
      - name: Run Snyk to check backend Docker image
        continue-on-error: true
        uses: snyk/actions/docker@b075801f26076be9bb50521154cafab73f44da0c
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ vars.DOCKER_USER }}/erp-solution-backend:test
          args: --file=backend/Dockerfile
      - name: Upload backend result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  snyk-frontend:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ vars.DOCKER_USER }}/erp-solution-frontend:test ./backend/frontend-react
      - name: Run Snyk to check frontend Docker image
        continue-on-error: true
        uses: snyk/actions/docker@b075801f26076be9bb50521154cafab73f44da0c
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ vars.DOCKER_USER }}/erp-solution-frontend:test
          args: --file=backend/frontend-react/Dockerfile
      - name: Upload frontend result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif